name: DiamondCompetition
version: '${project.version}'
main: net.kunmc.lab.diamondcompetition.DiamondCompetition
commands:
  diamondcompetition:
    usage: |-
      /diamondcompetition start
      /diamondcompetition stop
      /diamondcompetition config set <configItem> <value>
      /diamondcompetition config show
      /diamondcompetition shuffleplayers
    permission: op